In [ ]:
from typing import Callable
import numpy as np
from scipy.special import eval_legendre




def qm(l: np.ndarray, c0:float):
    mask = l>=2
    val = -2*c0*l/(2*l-1)
    val[mask] += -c0*l*(l-1)/(2*l-1)
    return val

def q0(l: np.ndarray, c0: float):
    return -l*(l+1)

def qp(l: np.ndarray, c0: float):
    return c0*(l+1)*(l+2)/(2*l+3) - 2*c0*(l+1)/(2*l+3)

def qm_lambda(l: np.ndarray, c0: float):
    return (l+1)/(2*l+1)

def qp_lambda(l: np.ndarray, c0: float):
    return (l+1)/(2*l+3)

def matrix_recurrences(
        qm: Callable[[np.ndarray, float], np.ndarray], 
        q0: Callable[[np.ndarray, float], np.ndarray],
        qp: Callable[[np.ndarray, float], np.ndarray],
        qm_lambda:  Callable[[np.ndarray, float], np.ndarray],
        qp_lambda:  Callable[[np.ndarray, float], np.ndarray],
        l_max: int,
        c0: float
        ): 
    A = np.zeros((l_max,l_max))
    B = np.zeros((l_max,l_max))
    l = np.arange(1,l_max+1)
    l_matrix = l-1 # the corresponding matrix entry indices; recurrence starts at l=1
    Qm = qm(l,c0)
    Q0 = q0(l,c0)
    Qp = qp(l,c0)
    Qm_lambda = qm_lambda(l,c0)
    Qp_lambda = qm_lambda(l,c0)
    A[l_matrix,l_matrix] = Qm
    A[l_matrix[1:],l_matrix[:-1]] = Q0
    A[l_matrix[2:],l_matrix[:-2]]= Qp
    B[l_matrix, l_matrix] = Qm_lambda
    B[l_matrix[1:], l_matrix[:-1]] = Qp_lambda[:-1]

    return A, B

# always shift indices -1 for the matrices

In [ ]:
A, B = matrix_recurrences(qm, q0, qp, qm_lambda, ...)

In [ ]:
c0 = 1.  # TODO  -- change, adjust

1


In [8]:
import numpy as np
N_max = 10
l_matrix = np.arange(0,N_max)
l_matrix,"i",  l_matrix[1:],"j", l_matrix[:-1]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'i',
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'j',
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [ ]:
# Solving for eigenvalues and eigenvectors

# np.linalg.eig()

In [ ]:
# Evaluation
Nth = 100
theta = np.linspace(0, np.pi, Nth)
x = np.cos(theta)

# TODO evaluate the function with x
# 