In [9]:
from typing import Callable
import numpy as np
import scipy
from scipy.special import eval_legendre

class Recurence:
    def __init__(self,l_max:int, c0:float):
        self.l_max = l_max
        self.c0 = c0

    def qm(self, l: np.ndarray, c0:float):
        mask = l>=2
        val = -2*c0*l/(2*l-1)
        val[mask] += -c0*l[mask]*(l[mask]-1)/(2*l[mask]-1)
        return val

    def q0(self, l: np.ndarray, c0: float):
        return -l*(l+1)

    def qp(self, l: np.ndarray, c0: float):
        return c0*(l+1)*(l+2)/(2*l+3) - 2*c0*(l+1)/(2*l+3)

    def qm_lambda(self, l: np.ndarray, c0: float):
        return l/(2*l-1)

    def qp_lambda(self, l: np.ndarray, c0: float):
        return (l+1)/(2*l+3)

    def generate_matrix(self): 
        l_max = self.l_max
        c0 = self.c0
        A = np.zeros((l_max,l_max))
        B = np.zeros((l_max,l_max))
        l = np.arange(1,l_max+1)
        l_matrix = l-1 # the corresponding matrix entry indices; recurrence starts at l=1
        Qm = self.qm(l,c0)
        Q0 = self.q0(l,c0)
        Qp = self.qp(l,c0)
        Qm_lambda = self.qm_lambda(l,c0)
        Qp_lambda = self.qp_lambda(l,c0)

        A[l_matrix,l_matrix] = Qm
        A[l_matrix[:-1],l_matrix[1:]] = Q0[:-1]
        A[l_matrix[:-2],l_matrix[2:]]= Qp[:-2]
        B[l_matrix, l_matrix] = Qm_lambda
        B[l_matrix[:-2], l_matrix[2:]] = Qp_lambda[:-2]

        return A, B

# always shift indices -1 for the matrices

In [16]:
rec = Recurence(l_max=10, c0=1.)
A, B = rec.generate_matrix()

np.set_printoptions(precision=3, suppress=True, linewidth=120)
print(A)
print(B)

[[ -2.     -2.      0.4     0.      0.      0.      0.      0.      0.      0.   ]
 [  0.     -2.     -6.      0.857   0.      0.      0.      0.      0.      0.   ]
 [  0.      0.     -2.4   -12.      1.333   0.      0.      0.      0.      0.   ]
 [  0.      0.      0.     -2.857 -20.      1.818   0.      0.      0.      0.   ]
 [  0.      0.      0.      0.     -3.333 -30.      2.308   0.      0.      0.   ]
 [  0.      0.      0.      0.      0.     -3.818 -42.      2.8     0.      0.   ]
 [  0.      0.      0.      0.      0.      0.     -4.308 -56.      3.294   0.   ]
 [  0.      0.      0.      0.      0.      0.      0.     -4.8   -72.      3.789]
 [  0.      0.      0.      0.      0.      0.      0.      0.     -5.294 -90.   ]
 [  0.      0.      0.      0.      0.      0.      0.      0.      0.     -5.789]]
[[1.    0.    0.4   0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.667 0.    0.429 0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.6   0.    0.444 0.    0.   

In [25]:
# Solving for eigenvalues and eigenvectors
rec = Recurence(l_max=10, c0=100)
A, B = rec.generate_matrix()
eig_vals, eig_vecs =scipy.linalg.eig(a=A,b=B)
eig_vals, eig_vecs, eig_vecs[:,4] # 4th eigenvector

(array([ -200.+0.j,  -300.+0.j,  -400.+0.j,  -500.+0.j,  -600.+0.j,  -700.+0.j,  -800.+0.j,  -900.+0.j, -1000.+0.j,
        -1100.+0.j]),
 array([[ 1.   ,  0.02 , -0.705, -0.071,  0.546,  0.136, -0.439, -0.207,  0.337,  0.275],
        [ 0.   ,  1.   ,  0.064, -0.908, -0.166,  0.787,  0.289, -0.654, -0.418,  0.49 ],
        [ 0.   ,  0.   ,  0.706,  0.081, -0.782, -0.207,  0.733,  0.359, -0.615, -0.514],
        [ 0.   ,  0.   ,  0.   ,  0.405,  0.083, -0.547, -0.215,  0.559,  0.372, -0.474],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.237,  0.069, -0.365, -0.189,  0.391,  0.338],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.128,  0.054, -0.223, -0.155,  0.248],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.07 ,  0.038, -0.132, -0.117],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.037,  0.027, -0.075],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.02 ,  0.017],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.

In [12]:
# Evaluation
Nth = 100
theta = np.linspace(0, np.pi, Nth)
x = np.cos(theta)

# TODO evaluate the function with x
# 