In [19]:
import numpy as np

ar = np.arange(1,11)
ar = np.arange(1,11)[None,:] * np.arange(1,11)[:,None]
mask = np.arange(1,11)>5

ar[:,mask]=0

print(ar)
idx_nonzero = np.nonzero(mask)
print(idx_nonzero[0])

ar[:,idx_nonzero]=1
print(ar)

ar_ref = ar[mask,:]
ar_ref[:,mask] = 0

ar[mask,:]=ar_ref
ar_ref

[[ 1  2  3  4  5  0  0  0  0  0]
 [ 2  4  6  8 10  0  0  0  0  0]
 [ 3  6  9 12 15  0  0  0  0  0]
 [ 4  8 12 16 20  0  0  0  0  0]
 [ 5 10 15 20 25  0  0  0  0  0]
 [ 6 12 18 24 30  0  0  0  0  0]
 [ 7 14 21 28 35  0  0  0  0  0]
 [ 8 16 24 32 40  0  0  0  0  0]
 [ 9 18 27 36 45  0  0  0  0  0]
 [10 20 30 40 50  0  0  0  0  0]]
[5 6 7 8 9]
[[ 1  2  3  4  5  1  1  1  1  1]
 [ 2  4  6  8 10  1  1  1  1  1]
 [ 3  6  9 12 15  1  1  1  1  1]
 [ 4  8 12 16 20  1  1  1  1  1]
 [ 5 10 15 20 25  1  1  1  1  1]
 [ 6 12 18 24 30  1  1  1  1  1]
 [ 7 14 21 28 35  1  1  1  1  1]
 [ 8 16 24 32 40  1  1  1  1  1]
 [ 9 18 27 36 45  1  1  1  1  1]
 [10 20 30 40 50  1  1  1  1  1]]


array([[ 6, 12, 18, 24, 30,  0,  0,  0,  0,  0],
       [ 7, 14, 21, 28, 35,  0,  0,  0,  0,  0],
       [ 8, 16, 24, 32, 40,  0,  0,  0,  0,  0],
       [ 9, 18, 27, 36, 45,  0,  0,  0,  0,  0],
       [10, 20, 30, 40, 50,  0,  0,  0,  0,  0]])